# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MZBet0tUzkL4BYZSlov5F-sAjRIMovlO

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

format(s)

"""*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

format(planet)

format(diameter)

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

format(s)

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

import numpy as np
arr=np.array([0,0,0,0,0,0,0,0,0])
print("***Numpy arrays iteams***")
print(arr)

import numpy as np
arr=np.array([5,5,5,5,5,5,5,5,5])
print("***Numpy array items***")
print(arr)

"""## 5. Create an array of all the even integers from 20 to 35"""

import numpy as np
arr=np.array([22,24,26,28,30,32,34])
print("numpy array iteams")
print(arr)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as np
x=np.arange(0,9).reshape (3,3)
print(x)

"""## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

import numpy as np
a=np.array ([1,2,3])
b=np.array ([4,5,6])
c=np.concatenate((a,b),axis=0)
print(c)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

import pandas as pd
data=[{'a':1,'b':2,'c':3}, {'a':10,'b':20,'c':30}] 
df=pd.DataFrame(data)
df

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

import pandas as pd
df=pd.date_range(start='1-1-2023',end='2-1-2023',freq='5H')
df

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

lists = [[1, 'aaa',22], [2, 'bbb', 25], [3, 'ccc', 24]]